//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardHeader
    {
        public int DocumentID { get; set; }
        public System.DateTime InputDate { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> PersonalNumber1 { get; set; }
        public Nullable<int> PersonalNumber2 { get; set; }
        public string Team { get; set; }
        public int Shift { get; set; }
        public string Machine { get; set; }
        public string Description { get; set; }
        public string Department { get; set; }
        public int Login { get; set; }
        public short addCapacity { get; set; }
    }
}
