//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardProduction
    {
        public int ID { get; set; }
        public int DocumentID { get; set; }
        public int MaterialID { get; set; }
        public int Cavity { get; set; }
        public Nullable<decimal> PlanQuantity { get; set; }
        public decimal CorrectQuantity { get; set; }
        public short IncorrectQuantity { get; set; }
        public short Fields { get; set; }
    }
}
