//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineSteps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MachineSteps()
        {
            this.CardSteps = new HashSet<CardSteps>();
        }
    
        public decimal Code { get; set; }
        public string DescriptionDE { get; set; }
        public string DescriptionEN { get; set; }
        public string DescriptionPL { get; set; }
        public string DescriptionTR { get; set; }
        public Nullable<bool> Active { get; set; }
        public string DescriptionES { get; set; }
        public string DescriptionCN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardSteps> CardSteps { get; set; }
    }
}
