//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class oeeEntities : DbContext
    {
        public oeeEntities()
            : base("name=oeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasicMaterial> BasicMaterial { get; set; }
        public virtual DbSet<CardHeader> CardHeader { get; set; }
        public virtual DbSet<CardProduction> CardProduction { get; set; }
        public virtual DbSet<CardSteps> CardSteps { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<MachineSteps> MachineSteps { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<User_Department> User_Department { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<ThProductionTime> ThProductionTime { get; set; }
        public virtual DbSet<View_all_stops> View_all_stops { get; set; }
        public virtual DbSet<view_DgrUretimTR> view_DgrUretimTR { get; set; }
        public virtual DbSet<view_EnjUretimTR> view_EnjUretimTR { get; set; }
        public virtual DbSet<view_material> view_material { get; set; }
        public virtual DbSet<view_production> view_production { get; set; }
        public virtual DbSet<view_production_quantity> view_production_quantity { get; set; }
        public virtual DbSet<view_production2> view_production2 { get; set; }
        public virtual DbSet<view_production3> view_production3 { get; set; }
        public virtual DbSet<view_remaining_stops> view_remaining_stops { get; set; }
        public virtual DbSet<view_sum_pause> view_sum_pause { get; set; }
        public virtual DbSet<view_th_machine_time> view_th_machine_time { get; set; }
        public virtual DbSet<view_TplUretimTR> view_TplUretimTR { get; set; }
        public virtual DbSet<View_UretimTR> View_UretimTR { get; set; }
    
        public virtual ObjectResult<sp_ProductSteps_Result> sp_ProductSteps(Nullable<System.DateTime> stepDate, string department)
        {
            var stepDateParameter = stepDate.HasValue ?
                new ObjectParameter("stepDate", stepDate) :
                new ObjectParameter("stepDate", typeof(System.DateTime));
    
            var departmentParameter = department != null ?
                new ObjectParameter("department", department) :
                new ObjectParameter("department", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProductSteps_Result>("sp_ProductSteps", stepDateParameter, departmentParameter);
        }
    
        public virtual ObjectResult<sp_OzetUretim_Result> sp_OzetUretim(Nullable<System.DateTime> tarih)
        {
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OzetUretim_Result>("sp_OzetUretim", tarihParameter);
        }
    }
}
