//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool ChangePassword { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public bool Active { get; set; }
        public bool AddingSheet { get; set; }
        public bool MainData { get; set; }
        public bool Reporting { get; set; }
        public string Werk { get; set; }
        public bool Alles { get; set; }
        public bool ChangeDepartment { get; set; }
        public Nullable<bool> Import { get; set; }
    }
}
