//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EnjUretimTR
    {
        public string Malzeme { get; set; }
        public System.DateTime Üretim_Tarihi { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public string İş_Yeri { get; set; }
    }
}
