//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_production2
    {
        public int DocumentID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string Team { get; set; }
        public int Shift { get; set; }
        public string Machine { get; set; }
        public string Department { get; set; }
        public string SAPName { get; set; }
        public int MaterialID { get; set; }
        public int Cavity { get; set; }
        public decimal CorrectQuantity { get; set; }
        public short IncorrectQuantity { get; set; }
        public short Fields { get; set; }
        public Nullable<decimal> MIN { get; set; }
        public Nullable<int> ProductionTime { get; set; }
        public short addCapacity { get; set; }
    }
}
