//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_production_quantity
    {
        public int DocumentID { get; set; }
        public Nullable<decimal> CorrectQuantity { get; set; }
        public Nullable<int> IncorrectQuantity { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public Nullable<int> ProdTime { get; set; }
    }
}
