//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UretimTR
    {
        public string Material { get; set; }
        public string KisaMetin { get; set; }
        public System.DateTime InputDate { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string Name { get; set; }
        public string Personel2 { get; set; }
        public string Team { get; set; }
        public int Shift { get; set; }
        public string Machine { get; set; }
        public string Aciklama { get; set; }
        public string Department { get; set; }
        public int Cavity { get; set; }
        public Nullable<decimal> PlanQuantity { get; set; }
        public decimal CorrectQuantity { get; set; }
        public short IncorrectQuantity { get; set; }
        public Nullable<int> Time { get; set; }
    }
}
