//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASTR.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int PersonalNumber { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string Company { get; set; }
        public string Werk { get; set; }
    }
}
